{{- if .Values.persistentVolumes.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: {{ template "emulatorjs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    volType: "data"
  name: {{ template "emulatorjs.fullname" . }}-data-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolumes.data.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: {{ .Values.persistentVolumes.data.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
{{- end -}}
