{{- if .Values.persistentVolumeClaims.config.enabled -}}
{{- if not .Values.persistentVolumeClaims.config.existingClaim -}}
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
{{- if .Values.persistentVolumeClaims.config.annotations }}
  annotations:
{{ toYaml .Values.persistentVolumeClaims.config.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "emulatorjs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.persistentVolumeClaims.config.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "emulatorjs.fullname" . }}-config
spec:
  accessModes:
{{ toYaml .Values.persistentVolumeClaims.config.accessModes | indent 4 }}
{{- if .Values.persistentVolumeClaims.config.storageClass }}
{{- if (eq "-" .Values.persistentVolumeClaims.config.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistentVolumeClaims.config.storageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistentVolumeClaims.config.size }}"
{{- end -}}
{{- end -}}
---
{{- if .Values.persistentVolumeClaims.data.enabled -}}
{{- if not .Values.persistentVolumeClaims.data.existingClaim -}}
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
{{- if .Values.persistentVolumeClaims.data.annotations }}
  annotations:
{{ toYaml .Values.persistentVolumeClaims.data.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "emulatorjs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.persistentVolumeClaims.data.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "emulatorjs.fullname" . }}-data
spec:
  accessModes:
{{ toYaml .Values.persistentVolumeClaims.data.accessModes | indent 4 }}
{{- if .Values.persistentVolumeClaims.data.storageClass }}
{{- if (eq "-" .Values.persistentVolumeClaims.data.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistentVolumeClaims.data.storageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistentVolumeClaims.data.size }}"
{{- end -}}
{{- end -}}
