apiVersion: v1
kind: Service

metadata:
  name: {{ .Chart.Name }}-{{ .Chart.AppVersion }}-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Chart.Name }}-{{ .Chart.Version }}
  labels:
    app: {{ .Chart.Name }}-{{ .Chart.Version }}

spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Chart.Version }}

  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.ip }}

  ports:
    - name: managementUIPort
      port: {{ .Values.env.managementUIPort }}
      targetPort: managementUIPort-tcp
      protocol: TCP

    - name: publicUIPort
      port: {{ .Values.env.publicUIPort }}
      targetPort: publicUIPort-tcp
      protocol: TCP

    {{- if .Values.env.ipfsPeeringPort }}
    - name: ipfsPeeringPort
      port: {{ .Values.env.ipfsPeeringPort }}
      targetPort: ipfsPeeringPort-tcp
      protocol: TCP
    {{ end }}
